/**
 * WooCommerce REST API Client for Astro
 * 
 * Auto-generated by PhantomWP
 * 
 * IMPORTANT: Configure your WooCommerce store URL in .env file:
 *   WC_API_URL=https://your-wordpress-site.com/wp-json
 * 
 * This client fetches products at build time for static generation.
 * For cart/checkout operations, see the cart-store and API routes.
 */

// Get WooCommerce API URL from environment variable
const WC_API_URL = import.meta.env.WC_API_URL || '';
const WC_ACCESS_SECRET = import.meta.env.WC_ACCESS_SECRET || '';

// Validate configuration
if (!WC_API_URL || WC_API_URL === '/wp-json' || !WC_API_URL.startsWith('http')) {
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
    console.error('\x1b[31m%s\x1b[0m', 'WooCommerce Configuration Error');
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
    console.error('\x1b[33m%s\x1b[0m', 'WC_API_URL is not configured or invalid.');
    console.error('\x1b[33m%s\x1b[0m', '');
    console.error('\x1b[33m%s\x1b[0m', 'To fix this, create a .env file in your project root:');
    console.error('\x1b[36m%s\x1b[0m', '');
    console.error('\x1b[36m%s\x1b[0m', '  WC_API_URL=https://your-wordpress-site.com/wp-json');
    console.error('\x1b[36m%s\x1b[0m', '  WC_ACCESS_SECRET=your_secret_key');
    console.error('\x1b[36m%s\x1b[0m', '');
    console.error('\x1b[33m%s\x1b[0m', 'Then restart the dev server.');
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
}

// Warn if using HTTP in production (credentials would be sent in plaintext)
if (WC_API_URL && WC_API_URL.startsWith('http://') && !import.meta.env.DEV) {
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
    console.error('\x1b[31m%s\x1b[0m', 'SECURITY WARNING: WC_API_URL uses HTTP');
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
    console.error('\x1b[33m%s\x1b[0m', 'API credentials are being sent over an unencrypted connection.');
    console.error('\x1b[33m%s\x1b[0m', 'Change WC_API_URL to use HTTPS in production.');
    console.error('\x1b[31m%s\x1b[0m', '='.repeat(60));
}

// ============================================================================
// Types - Store API Response Format
// ============================================================================

export interface WCProductImage {
    id: number;
    src: string;
    thumbnail: string;
    srcset: string;
    sizes: string;
    name: string;
    alt: string;
}

export interface WCProductCategory {
    id: number;
    name: string;
    slug: string;
}

export interface WCProductTag {
    id: number;
    name: string;
    slug: string;
}

export interface WCProductAttribute {
    id: number;
    name: string;
    taxonomy: string;
    has_variations: boolean;
    terms: Array<{ id: number; name: string; slug: string }>;
}

export interface WCProductPrices {
    price: string;
    regular_price: string;
    sale_price: string;
    price_range: { min_amount: string; max_amount: string } | null;
    currency_code: string;
    currency_symbol: string;
    currency_minor_unit: number;
    currency_decimal_separator: string;
    currency_thousand_separator: string;
    currency_prefix: string;
    currency_suffix: string;
}

/**
 * WooCommerce Store API Product Format
 * Note: This differs from REST API v3 format
 */
export interface WCProduct {
    id: number;
    name: string;
    slug: string;
    parent: number;
    type: 'simple' | 'variable' | 'grouped' | 'external';
    variation: string;
    permalink: string;
    sku: string;
    short_description: string;
    description: string;
    on_sale: boolean;
    prices: WCProductPrices;
    price_html: string;
    average_rating: string;
    review_count: number;
    images: WCProductImage[];
    categories: WCProductCategory[];
    tags: WCProductTag[];
    attributes: WCProductAttribute[];
    variations: Array<{ id: number; attributes: Array<{ name: string; value: string }> }>;
    has_options: boolean;
    is_purchasable: boolean;
    is_in_stock: boolean;
    is_on_backorder: boolean;
    low_stock_remaining: number | null;
    sold_individually: boolean;
    add_to_cart: {
        text: string;
        description: string;
        url: string;
        minimum: number;
        maximum: number;
        multiple_of: number;
    };
    // Normalized fields (added by our helper)
    price?: string;
    regular_price?: string;
    sale_price?: string;
    stock_status?: 'instock' | 'outofstock' | 'onbackorder';
    purchasable?: boolean;
    featured?: boolean;
    rating_count?: number;
}

export interface WCProductVariation {
    id: number;
    sku: string;
    price: string;
    regular_price: string;
    sale_price: string;
    on_sale: boolean;
    purchasable: boolean;
    stock_status: 'instock' | 'outofstock' | 'onbackorder';
    stock_quantity: number | null;
    image: WCProductImage;
    attributes: Array<{ id: number; name: string; option: string }>;
}

export interface WCCategory {
    id: number;
    name: string;
    slug: string;
    parent: number;
    description: string;
    count: number;
    image: WCProductImage | null;
}

// ============================================================================
// Fetch Helper
// ============================================================================

/**
 * Build headers for WooCommerce API requests
 * Includes the secret header for authenticated server-side requests
 */
function buildHeaders(): Record<string, string> {
    const headers: Record<string, string> = {
        'Accept': 'application/json',
    };
    
    if (WC_ACCESS_SECRET) {
        headers['X-PhantomWP-Secret'] = WC_ACCESS_SECRET;
    }
    
    return headers;
}

/**
 * Generic WooCommerce API fetch helper
 * Uses the WooCommerce Store API (public) for product data
 */
async function wcFetch<T>(
    endpoint: string, 
    params: Record<string, any> = {}, 
    defaultValue?: T
): Promise<T> {
    // Check if WC_API_URL is properly configured
    if (!WC_API_URL || !WC_API_URL.startsWith('http')) {
        console.warn(`[WooCommerce] Skipping API call to ${endpoint} - WC_API_URL not configured`);
        return defaultValue as T;
    }
    
    let url: URL;
    try {
        url = new URL(`${WC_API_URL}/wc/store/v1/${endpoint}`);
    } catch (e) {
        console.error(`[WooCommerce] Invalid API URL: ${WC_API_URL}`);
        return defaultValue as T;
    }
    
    Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
            if (Array.isArray(value)) {
                url.searchParams.set(key, value.join(','));
            } else {
                url.searchParams.set(key, String(value));
            }
        }
    });
    
    try {
        const response = await fetch(url.toString(), {
            headers: buildHeaders(),
        });
        
        if (!response.ok) {
            console.error(`WooCommerce API error: ${response.status} ${response.statusText}`);
            return defaultValue as T;
        }
        
        return response.json();
    } catch (error) {
        console.error(`WooCommerce API connection failed for ${endpoint}:`, error instanceof Error ? error.message : error);
        return defaultValue as T;
    }
}

/**
 * Fetch from WooCommerce REST API v3 (requires consumer key/secret)
 * Used for operations that need more data than Store API provides
 */
async function wcRestFetch<T>(
    endpoint: string, 
    params: Record<string, any> = {}, 
    defaultValue?: T
): Promise<T> {
    // Check if WC_API_URL is properly configured
    if (!WC_API_URL || !WC_API_URL.startsWith('http')) {
        console.warn(`[WooCommerce] Skipping REST API call to ${endpoint} - WC_API_URL not configured`);
        return defaultValue as T;
    }
    
    let url: URL;
    try {
        url = new URL(`${WC_API_URL}/wc/v3/${endpoint}`);
    } catch (e) {
        console.error(`[WooCommerce] Invalid API URL: ${WC_API_URL}`);
        return defaultValue as T;
    }
    
    Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
            if (Array.isArray(value)) {
                url.searchParams.set(key, value.join(','));
            } else {
                url.searchParams.set(key, String(value));
            }
        }
    });
    
    // Use HTTP Basic Auth instead of query params to keep credentials out of logs
    const consumerKey = import.meta.env.WC_CONSUMER_KEY;
    const consumerSecret = import.meta.env.WC_CONSUMER_SECRET;
    const headers = buildHeaders();
    if (consumerKey && consumerSecret) {
        headers['Authorization'] = `Basic ${btoa(`${consumerKey}:${consumerSecret}`)}`;
    }
    
    try {
        const response = await fetch(url.toString(), { headers });
        
        if (!response.ok) {
            console.error(`WooCommerce REST API error: ${response.status} ${response.statusText}`);
            return defaultValue as T;
        }
        
        return response.json();
    } catch (error) {
        console.error(`WooCommerce REST API connection failed for ${endpoint}:`, error instanceof Error ? error.message : error);
        return defaultValue as T;
    }
}

// ============================================================================
// Product Normalizer
// ============================================================================

/**
 * Convert Store API price (in minor units) to decimal string
 */
function normalizePrice(price: string, minorUnit: number): string {
    if (!price) return '';
    const value = parseInt(price, 10);
    if (isNaN(value)) return price;
    return (value / Math.pow(10, minorUnit)).toFixed(2);
}

/**
 * Normalize a Store API product to include backwards-compatible fields
 */
function normalizeProduct(product: WCProduct): WCProduct {
    if (!product) return product;
    
    const minorUnit = product.prices?.currency_minor_unit || 2;
    
    return {
        ...product,
        // Add normalized price fields for backwards compatibility
        price: normalizePrice(product.prices?.price || '', minorUnit),
        regular_price: normalizePrice(product.prices?.regular_price || '', minorUnit),
        sale_price: normalizePrice(product.prices?.sale_price || '', minorUnit),
        // Add normalized stock status
        stock_status: product.is_in_stock ? 'instock' : (product.is_on_backorder ? 'onbackorder' : 'outofstock'),
        purchasable: product.is_purchasable,
        // Featured is not in Store API, default to false
        featured: false,
        rating_count: product.review_count,
    };
}

// ============================================================================
// Products
// ============================================================================

export interface GetProductsOptions {
    page?: number;
    perPage?: number;
    per_page?: number;
    search?: string;
    category?: number;
    tag?: number;
    featured?: boolean;
    onSale?: boolean;
    minPrice?: string;
    maxPrice?: string;
    stockStatus?: 'instock' | 'outofstock' | 'onbackorder';
    orderBy?: 'date' | 'id' | 'title' | 'slug' | 'price' | 'popularity' | 'rating';
    order?: 'asc' | 'desc';
}

/**
 * Get products from WooCommerce
 * Uses Store API for public product data
 */
export async function getProducts(options: GetProductsOptions = {}): Promise<WCProduct[]> {
    const products = await wcFetch<WCProduct[]>('products', {
        page: options.page,
        per_page: options.perPage || options.per_page || 10,
        search: options.search,
        category: options.category,
        tag: options.tag,
        on_sale: options.onSale,
        min_price: options.minPrice,
        max_price: options.maxPrice,
        stock_status: options.stockStatus,
        orderby: options.orderBy || 'date',
        order: options.order || 'desc',
    }, []);
    
    // Normalize all products
    return products.map(normalizeProduct);
}

/**
 * Get all products (paginated fetch)
 */
export async function getAllProducts(): Promise<WCProduct[]> {
    const allProducts: WCProduct[] = [];
    let page = 1;
    let hasMore = true;
    
    while (hasMore) {
        const products = await getProducts({ page, perPage: 100 });
        allProducts.push(...products);
        hasMore = products.length === 100;
        page++;
        
        // Safety limit
        if (page > 50) break;
    }
    
    return allProducts;
}

/**
 * Get a single product by slug
 */
export async function getProduct(slug: string): Promise<WCProduct | null> {
    const products = await wcFetch<WCProduct[]>('products', { slug }, []);
    if (products && products.length > 0) {
        return normalizeProduct(products[0]);
    }
    return null;
}

/**
 * Get a single product by ID
 */
export async function getProductById(id: number): Promise<WCProduct | null> {
    const product = await wcFetch<WCProduct | null>(`products/${id}`, {}, null);
    return product ? normalizeProduct(product) : null;
}

/**
 * Get product variations (for variable products)
 */
export async function getProductVariations(productId: number): Promise<WCProductVariation[]> {
    return wcRestFetch<WCProductVariation[]>(`products/${productId}/variations`, { per_page: 100 }, []);
}

/**
 * Get featured products
 */
export async function getFeaturedProducts(limit: number = 8): Promise<WCProduct[]> {
    return getProducts({ featured: true, perPage: limit });
}

/**
 * Get products on sale
 */
export async function getOnSaleProducts(limit: number = 8): Promise<WCProduct[]> {
    return getProducts({ onSale: true, perPage: limit });
}

/**
 * Get related products
 */
export async function getRelatedProducts(product: WCProduct, limit: number = 4): Promise<WCProduct[]> {
    if (!product.related_ids || product.related_ids.length === 0) {
        // Fall back to products in same category
        if (product.categories.length > 0) {
            return getProducts({ category: product.categories[0].id, perPage: limit });
        }
        return [];
    }
    
    // Fetch related products by ID
    const related: WCProduct[] = [];
    for (const id of product.related_ids.slice(0, limit)) {
        const p = await getProductById(id);
        if (p) related.push(p);
    }
    return related;
}

// ============================================================================
// Categories
// ============================================================================

/**
 * Get all product categories
 */
export async function getProductCategories(): Promise<WCCategory[]> {
    return wcFetch<WCCategory[]>('products/categories', { per_page: 100 }, []);
}

/**
 * Get category by slug
 */
export async function getProductCategoryBySlug(slug: string): Promise<WCCategory | null> {
    const categories = await wcFetch<WCCategory[]>('products/categories', { slug }, []);
    return categories && categories.length > 0 ? categories[0] : null;
}

/**
 * Get products by category slug
 */
export async function getProductsByCategory(categorySlug: string): Promise<WCProduct[]> {
    const category = await getProductCategoryBySlug(categorySlug);
    if (!category) return [];
    return getProducts({ category: category.id, perPage: 100 });
}

/**
 * Get top-level categories (no parent)
 */
export async function getTopLevelCategories(): Promise<WCCategory[]> {
    const all = await getProductCategories();
    return all.filter(cat => cat.parent === 0);
}

/**
 * Get child categories for a parent
 */
export async function getChildCategories(parentId: number): Promise<WCCategory[]> {
    const all = await getProductCategories();
    return all.filter(cat => cat.parent === parentId);
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Format price with currency
 * Uses product.prices if available (Store API), otherwise falls back to manual formatting
 * @param price - Price string or product object
 * @param currencyOrProduct - Currency code (default: USD) or product for Store API prices
 * @param locale - Locale for formatting (default: en-US)
 */
export function formatPrice(
    price: string | number | WCProduct, 
    currencyOrProduct: string | WCProduct = 'USD',
    locale: string = 'en-US'
): string {
    // If passed a product directly, use its price_html or format from prices
    if (typeof price === 'object' && 'prices' in price) {
        const product = price;
        if (product.price_html) {
            // Strip HTML tags for plain text
            return product.price_html.replace(/<[^>]*>/g, '').trim();
        }
        if (product.prices) {
            const { currency_prefix, currency_suffix, price: priceValue, currency_minor_unit } = product.prices;
            const numPrice = parseInt(priceValue, 10) / Math.pow(10, currency_minor_unit || 2);
            return `${currency_prefix || ''}${numPrice.toFixed(2)}${currency_suffix || ''}`;
        }
    }
    
    // Standard formatting for string/number prices
    const numericPrice = typeof price === 'string' ? parseFloat(price) : (typeof price === 'number' ? price : 0);
    if (isNaN(numericPrice)) return '';
    
    const currency = typeof currencyOrProduct === 'string' ? currencyOrProduct : 'USD';
    
    return new Intl.NumberFormat(locale, {
        style: 'currency',
        currency,
    }).format(numericPrice);
}

/**
 * Get the main product image URL
 * Store API provides: src (full), thumbnail
 */
export function getProductImageUrl(product: WCProduct, size: 'thumbnail' | 'medium' | 'large' | 'full' = 'full'): string | null {
    const image = product.images?.[0];
    if (!image) return null;
    
    // Store API returns thumbnail and src (full)
    if (size === 'thumbnail' && image.thumbnail) {
        return image.thumbnail;
    }
    
    // Return full size image
    return image.src || null;
}

/**
 * Check if product is in stock
 * Uses Store API is_in_stock first, falls back to normalized stock_status
 */
export function isInStock(product: WCProduct): boolean {
    // Store API field (preferred)
    if (typeof product.is_in_stock === 'boolean') {
        return product.is_in_stock && (product.is_purchasable !== false);
    }
    // Normalized field (backwards compat)
    return product.stock_status === 'instock' && product.purchasable !== false;
}

/**
 * Get discount percentage
 */
export function getDiscountPercentage(product: WCProduct): number | null {
    if (!product.on_sale) return null;
    
    // Try normalized prices first
    let regular = parseFloat(product.regular_price || '');
    let sale = parseFloat(product.sale_price || '');
    
    // Fall back to prices object from Store API
    if (isNaN(regular) || isNaN(sale) || regular === 0) {
        if (!product.prices) return null;
        const minorUnit = product.prices.currency_minor_unit || 2;
        regular = parseInt(product.prices.regular_price, 10) / Math.pow(10, minorUnit);
        sale = parseInt(product.prices.sale_price, 10) / Math.pow(10, minorUnit);
    }
    
    if (isNaN(regular) || isNaN(sale) || regular === 0) return null;
    
    return Math.round(((regular - sale) / regular) * 100);
}

/**
 * Decode HTML entities in text (e.g. &amp; -> &, &lt; -> <)
 */
export function decodeEntities(text: string): string {
    if (!text) return '';
    return text
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#0?39;/g, "'")
        .replace(/&nbsp;/g, ' ');
}

/**
 * Strip HTML from description
 */
export function stripHtml(html: string): string {
    if (!html) return '';
    return html
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/\s+/g, ' ')
        .trim();
}

/**
 * Truncate text with ellipsis
 */
export function truncate(text: string, maxLength: number = 150): string {
    if (!text) return '';
    const stripped = stripHtml(text);
    if (stripped.length <= maxLength) return stripped;
    return stripped.substring(0, maxLength).trim() + '...';
}
