/**
 * PhantomWP Dev Tools
 * Auto-managed by PhantomWP infrastructure -- do not edit this file.
 * To update: use the Infrastructure modal in the PhantomWP editor.
 */

/**
 * Vite plugin: inject data-component attributes on .astro components in dev mode
 * so the IDE element inspector can identify which component file rendered each DOM element.
 * Also proxies /media/cms/* requests from WordPress when files haven't been downloaded yet.
 * Only active in dev (serve) mode -- no impact on production builds.
 */
export function devComponentIdPlugin() {
    let wpConfig = null;
    let reverseMap = null;
    let wpConfigLoaded = false;

    function loadWpConfig(root, fs, path) {
        if (wpConfigLoaded) return;
        wpConfigLoaded = true;
        try {
            const wpPath = path.join(root, 'src/lib/wordpress.ts');
            if (!fs.existsSync(wpPath)) return;
            const content = fs.readFileSync(wpPath, 'utf-8');
            const urlMatch = content.match(/(?:WORDPRESS_API_URL|WP_API_URL)\s*=\s*['"]([^'"]+)['"]/);
            if (!urlMatch) return;
            const secretMatch = content.match(/WP_ACCESS_SECRET\s*=.*\|\|\s*'([^']*)'/);
            const imageSourceMatch = content.match(/IMAGE_SOURCE_MODE[^']*'(local|cdn)'/);
            if (imageSourceMatch && imageSourceMatch[1] === 'cdn') return;
            wpConfig = {
                siteUrl: urlMatch[1].replace(/\/wp-json.*$/, ''),
                secret: secretMatch ? secretMatch[1] : '',
            };
        } catch { /* no config available */ }
    }

    function loadReverseMap(root, fs, path) {
        if (reverseMap) return reverseMap;
        reverseMap = {};
        try {
            const mapPath = path.join(root, 'src/lib/media-map.json');
            if (!fs.existsSync(mapPath)) return reverseMap;
            const map = JSON.parse(fs.readFileSync(mapPath, 'utf-8'));
            for (const [wpUrl, localPath] of Object.entries(map)) {
                reverseMap[localPath] = wpUrl;
            }
        } catch { /* empty map */ }
        return reverseMap;
    }

    function normalizeForLookup(filename) {
        return filename
            .replace(/-\d+x\d+(?=\.[^.]+$)/, '')
            .replace(/\.[^.]+$/, '')
            .replace(/[^a-z0-9_-]/gi, '_')
            .toLowerCase();
    }

    return {
        name: 'phantom-dev-tools',
        enforce: 'pre',
        apply: 'serve',
        async load(id) {
            if (!id.endsWith('.astro') || id.includes('?')) return null;
            const relative = id.includes('/src/') ? id.substring(id.indexOf('/src/') + 1) : null;
            if (!relative) return null;
            if (!relative.startsWith('src/components/') && !relative.startsWith('src/layouts/')) return null;

            const { readFile } = await import('node:fs/promises');
            let code;
            try { code = await readFile(id, 'utf-8'); } catch { return null; }

            if (code.includes('data-component=')) return null;

            const fmStart = code.indexOf('---');
            if (fmStart === -1) return null;
            const fmEnd = code.indexOf('---', fmStart + 3);
            if (fmEnd === -1) return null;
            const templateStart = fmEnd + 3;
            const template = code.substring(templateStart);

            const tagMatch = template.match(/(<[a-zA-Z][\w.-]*)(\s|>)/);
            if (!tagMatch) return null;

            const insertPos = templateStart + tagMatch.index + tagMatch[1].length;
            const attr = ' data-component="' + relative + '"';

            return code.substring(0, insertPos) + attr + code.substring(insertPos);
        },
        configureServer(server) {
            server.middlewares.use(async (req, res, next) => {
                if (!req.url || !req.url.startsWith('/media/cms/')) return next();

                const fs = await import('node:fs');
                const path = await import('node:path');
                const root = server.config.root;
                loadWpConfig(root, fs, path);
                if (!wpConfig) return next();

                const requestedPath = req.url.split('?')[0];

                const publicFile = path.join(root, 'public', requestedPath);
                if (fs.existsSync(publicFile)) return next();

                const srcFile = path.join(root, 'src', requestedPath.replace('/media/cms/', 'media/cms/'));
                if (fs.existsSync(srcFile)) return next();

                const rMap = loadReverseMap(root, fs, path);
                let wpUrl = rMap[requestedPath];

                if (!wpUrl) {
                    const filename = requestedPath.split('/').pop() || '';
                    const normalized = normalizeForLookup(filename);
                    for (const [localPath, remoteUrl] of Object.entries(rMap)) {
                        const localFilename = localPath.split('/').pop() || '';
                        if (normalizeForLookup(localFilename) === normalized) {
                            wpUrl = remoteUrl;
                            break;
                        }
                    }
                }

                if (!wpUrl) {
                    const filename = requestedPath.split('/').pop() || '';
                    const searchName = filename
                        .replace(/\.webp$/, '')
                        .replace(/[_-]/g, ' ')
                        .trim();
                    try {
                        const headers = { 'Accept': 'application/json' };
                        if (wpConfig.secret) headers['X-PhantomWP-Secret'] = wpConfig.secret;
                        const searchUrl = wpConfig.siteUrl + '/wp-json/wp/v2/media?search=' + encodeURIComponent(searchName) + '&per_page=10';
                        const searchRes = await fetch(searchUrl, { headers });
                        if (searchRes.ok) {
                            const items = await searchRes.json();
                            const normalizedReq = normalizeForLookup(filename);
                            for (const item of items) {
                                if (!item.source_url) continue;
                                const itemFilename = item.source_url.split('/').pop() || '';
                                if (normalizeForLookup(itemFilename) === normalizedReq) {
                                    wpUrl = item.source_url;
                                    break;
                                }
                            }
                            if (!wpUrl && items.length > 0 && items[0].source_url) {
                                wpUrl = items[0].source_url;
                            }
                        }
                    } catch { /* search failed, fall through */ }
                }

                if (!wpUrl) return next();

                try {
                    const headers = {};
                    if (wpConfig.secret) headers['X-PhantomWP-Secret'] = wpConfig.secret;
                    const imgRes = await fetch(wpUrl, { headers });
                    if (!imgRes.ok) return next();

                    const contentType = imgRes.headers.get('content-type') || 'image/jpeg';
                    res.setHeader('Content-Type', contentType);
                    res.setHeader('Cache-Control', 'public, max-age=86400');
                    res.setHeader('X-Proxied-From', 'wordpress');

                    const buffer = Buffer.from(await imgRes.arrayBuffer());
                    res.end(buffer);
                } catch {
                    return next();
                }
            });
        },
    };
}
